# Generated by Django 5.1.3 on 2024-11-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_renterrange_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bike",
            name="size",
            field=models.FloatField(
                choices=[(1, "Normal"), (1.5, "Chonky")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="storagerange",
            name="end_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
