# Generated by Django 5.1.3 on 2024-11-20 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_alter_bike_size_alter_storagerange_end_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bike",
            name="size",
        ),
    ]
