# Generated by Django 5.1.3 on 2024-11-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_remove_bike_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="renter",
            name="access",
            field=models.BooleanField(default=False),
        ),
    ]
