# Generated by Django 5.1.3 on 2024-11-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_renter_access"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="renter",
            name="access",
        ),
        migrations.AddField(
            model_name="renterrange",
            name="access",
            field=models.BooleanField(default=False),
        ),
    ]
