# Generated by Django 5.1.3 on 2024-12-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_alter_renterrange_access"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, default=None, null=True)),
                (
                    "key",
                    models.CharField(
                        choices=[("SHOP", "Shop"), ("STORAGE", "Storage")],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
