# Generated by Django 5.1.3 on 2024-12-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_rentcost"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentcost",
            name="cost",
            field=models.IntegerField(default=0),
        ),
    ]
