# Generated by Django 5.1.3 on 2024-12-22 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_rentcost_cost"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentPaid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_paid", models.DateField()),
                ("amount_paid", models.IntegerField(default=0)),
                (
                    "renter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.renter"
                    ),
                ),
            ],
        ),
    ]
