# Generated by Django 5.1.3 on 2024-12-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_rentpaid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rentcost",
            options={"verbose_name": "Rent Cost", "verbose_name_plural": "Rent Cost"},
        ),
        migrations.AlterModelOptions(
            name="renterrange",
            options={
                "verbose_name": "Renter Range",
                "verbose_name_plural": "Renter Ranges",
            },
        ),
        migrations.AlterModelOptions(
            name="rentpaid",
            options={"verbose_name": "Rent Paid", "verbose_name_plural": "Rent Paid"},
        ),
        migrations.AlterModelOptions(
            name="storagerange",
            options={
                "verbose_name": "Storage Range",
                "verbose_name_plural": "Storage Ranges",
            },
        ),
        migrations.AlterField(
            model_name="rentcost",
            name="key",
            field=models.CharField(
                choices=[("RENT", "Rent"), ("SHOP", "Shop"), ("STORAGE", "Storage")],
                max_length=10,
            ),
        ),
    ]
