# Generated by Django 5.1.3 on 2025-04-02 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_alter_rentcost_options_alter_renterrange_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bike",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bikes",
                to="shop.renter",
            ),
        ),
    ]
